#ifndef LIBFLYADMINTIME_GLOBAL_H
#define LIBFLYADMINTIME_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FLYADMINTIME_LIBRARY)
#  define FLYADMINTIME_EXPORT Q_DECL_EXPORT
#else
#  define FLYADMINTIME_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBFLYADMINTIME_GLOBAL_H
