#ifndef FLYPHONEDBUS_GLOBAL_H
#define FLYPHONEDBUS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FLYPHONEDBUS_LIBRARY)
#  define FLYPHONEDBUSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FLYPHONEDBUSSHARED_EXPORT Q_DECL_IMPORT
#endif

#define DBUS_SERVICE_NAME "org.fly.phone.launcher"

#endif // FLYPHONEDBUS_GLOBAL_H
