#ifndef ORBIT_CONFIG_H
#define ORBIT_CONFIG_H 1

#define ORBIT_CONFIG_SERIAL 20
#ifndef ORBIT_MAJOR_VERSION
#define ORBIT_MAJOR_VERSION (2)
#define ORBIT_MINOR_VERSION (14)
#define ORBIT_MICRO_VERSION (19)
#endif

#define ORBIT_IMPLEMENTS_IS_A 1

/*
 * Alignment of CORBA types mapped to C.
 * These have *nothing* to do with CDR alignment.
 */
#define ORBIT_ALIGNOF_CORBA_OCTET        0
#define ORBIT_ALIGNOF_CORBA_BOOLEAN      0
#define ORBIT_ALIGNOF_CORBA_CHAR         0
#define ORBIT_ALIGNOF_CORBA_WCHAR        0
#define ORBIT_ALIGNOF_CORBA_SHORT        0
#define ORBIT_ALIGNOF_CORBA_LONG         0
#define ORBIT_ALIGNOF_CORBA_LONG_LONG    0
#define ORBIT_ALIGNOF_CORBA_FLOAT        0
#define ORBIT_ALIGNOF_CORBA_DOUBLE       0
#define ORBIT_ALIGNOF_CORBA_LONG_DOUBLE  0
#define ORBIT_ALIGNOF_CORBA_STRUCT       0
#define ORBIT_ALIGNOF_CORBA_POINTER      0

#endif
