/* Generated by meson */

/**
 * TRACKER_MAJOR_VERSION:
 *
 * The major version of the Tracker library.
 *
 * Like #tracker_major_version, but intended to be used at application compile time.
 */
#define TRACKER_MAJOR_VERSION 3

/**
 * TRACKER_MINOR_VERSION:
 *
 * The minor version of the Tracker library.
 *
 * Like #tracker_minor_version, but intended to be used at application compile time.
 */
#define TRACKER_MINOR_VERSION 7

/**
 * TRACKER_MICRO_VERSION:
 *
 * The micro version of the Tracker library.
 *
 * Like #tracker_micro_version, but intended to be used at application compile time.
 */
#define TRACKER_MICRO_VERSION 3
