// This file was generated by ecm_setup_version(): DO NOT EDIT!

#ifndef PACKAGE_VERSION_H
#define PACKAGE_VERSION_H

#define PACKAGE_VERSION_STRING "5.110.0"
#define PACKAGE_VERSION_MAJOR 5
#define PACKAGE_VERSION_MINOR 110
#define PACKAGE_VERSION_PATCH 0
#define PACKAGE_VERSION ((5<<16)|(110<<8)|(0))

#endif
