// This file was generated by ecm_setup_version(): DO NOT EDIT!

#ifndef KPARTS_VERSION_H
#define KPARTS_VERSION_H

#define KPARTS_VERSION_STRING "5.110.0"
#define KPARTS_VERSION_MAJOR 5
#define KPARTS_VERSION_MINOR 110
#define KPARTS_VERSION_PATCH 0
#define KPARTS_VERSION ((5<<16)|(110<<8)|(0))

#endif
