// This file was generated by ecm_setup_version(): DO NOT EDIT!

#ifndef PLASMA_VERSION_H
#define PLASMA_VERSION_H

#define PLASMA_VERSION_STRING "5.99.0"
#define PLASMA_VERSION_MAJOR 5
#define PLASMA_VERSION_MINOR 99
#define PLASMA_VERSION_PATCH 0
#define PLASMA_VERSION ((5<<16)|(99<<8)|(0))

#endif
