/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -p battery1_p.h:battery1.cpp org.bluez.Battery1.xml
 *
 * qdbusxml2cpp is Copyright (C) 2018 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef BATTERY1_P_H
#define BATTERY1_P_H

#include <qt/QtCore/QObject>
#include <qt/QtCore/QByteArray>
#include <qt/QtCore/QList>
#include <qt/QtCore/QMap>
#include <qt/QtCore/QString>
#include <qt/QtCore/QStringList>
#include <qt/QtCore/QVariant>
#include <qt/QtDBus/QtDBus>

/*
 * Proxy class for interface org.bluez.Battery1
 */
class OrgBluezBattery1Interface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.bluez.Battery1"; }

public:
    OrgBluezBattery1Interface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = nullptr);

    ~OrgBluezBattery1Interface();

    Q_PROPERTY(uchar Percentage READ percentage)
    inline uchar percentage() const
    { return qvariant_cast< uchar >(property("Percentage")); }

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
};

namespace org {
  namespace bluez {
    typedef ::OrgBluezBattery1Interface Battery1;
  }
}
#endif
