// This file was generated by ecm_setup_version(): DO NOT EDIT!

#ifndef KDOCTOOLS_VERSION_H
#define KDOCTOOLS_VERSION_H

#define KDOCTOOLS_VERSION_STRING "5.110.0"
#define KDOCTOOLS_VERSION_MAJOR 5
#define KDOCTOOLS_VERSION_MINOR 110
#define KDOCTOOLS_VERSION_PATCH 0
#define KDOCTOOLS_VERSION ((5<<16)|(110<<8)|(0))

#endif
